// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFS-32bD-wNeQPrcDSmWtSxgIuaHEv3r0',
    appId: '1:533645470722:web:137dc8af73dd0c2a47cb1b',
    messagingSenderId: '533645470722',
    projectId: 'shopnow-4ca46',
    authDomain: 'shopnow-4ca46.firebaseapp.com',
    storageBucket: 'shopnow-4ca46.firebasestorage.app',
    measurementId: 'G-3QWMPDK5XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYRXnysX9u3ty-e0sgVr_xKFGiUDVuSw',
    appId: '1:533645470722:android:7ee7470b4c0fe37b47cb1b',
    messagingSenderId: '533645470722',
    projectId: 'shopnow-4ca46',
    storageBucket: 'shopnow-4ca46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzYng-1-UXL8Qpn3SRtyGZJjCDOMGOKi4',
    appId: '1:533645470722:ios:3450a747e9437c3347cb1b',
    messagingSenderId: '533645470722',
    projectId: 'shopnow-4ca46',
    storageBucket: 'shopnow-4ca46.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzYng-1-UXL8Qpn3SRtyGZJjCDOMGOKi4',
    appId: '1:533645470722:ios:3450a747e9437c3347cb1b',
    messagingSenderId: '533645470722',
    projectId: 'shopnow-4ca46',
    storageBucket: 'shopnow-4ca46.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
